

export const Paths = {
    Route: { path: "/" },

    // pages
    Signin: { path: "/login" },
    DashboardOverview: { path: "/dashboard" },
    Users: { path: "/user/list" },
    EditUser: { path: "/user/edit/:id" },
    CreateQuestionnaire: { path: "/questionnaire/list" },
    SendSegments: { path: "/message/send/segment" },
    TemplateMessages: { path: "/message/template/list" },
    CreateMessage: { path: "/message/template/create" },
    EditMessage: { path: "/message/template/edit/:id" },
    SendHistories: { path: "/message/send/list" },
    SendHistoryDetail: { path: "/message/send/detail/:id" },
    Privileges: { path: "/privilege" },
    VisitorHistories: { path: "/visitor/history" },
    EditVisitorHistory: { path: "/visitor/history/edit/:id" },
    Products: { path: "/product/list" },
    Products_: { path: "/product/list_" },
    ProductCategory: { path: "/product/category" },
    EditProduct: { path: "/product/edit/:id" },
    CreateProduct: { path: "/product/create" },
    OrderDetail: { path: "/product/detail/:id" },
    Coupons: { path: "/coupon/list" },
    CreateCoupon: { path: "/coupon/create" },
    Orders: { path: "/order/list" },
    Reserves: { path: "/reserve/list" },
    EventCalendar: { path: "/event/calendar" },
    Events: { path: "/event/list" },
    ScheduleCalendar: { path: "/schedule/calendar" },
    Schedules: { path: "/schedule/list" },
    Invitations: { path: "/invitation/list" },
    EditInvitation: { path: "/invitation/edit/:id" },
    PrivacyPolicy: { path: "/setting/privacy-policy" },
    TermsOfService: { path: "/setting/terms-of-service" },
    SpecificTrades: { path: "/setting/specific-trades" },
    Tags: { path: "/tag" },
    QrCode: { path: "/qr-code" },
    Api: {path: "/api"},
    Greeting: {path: "/greeting"},


    // LIFF
    LiffProductDetail: { path: "/liff/product/detail/:id" },
    LiffProducts: { path: "/liff/product/list" },
    LiffProductCategories: { path: "/liff/product/category/:id" },
    LiffCarts: { path: "/cart" },
    LiffCheckout: { path: "/checkout" },
    LiffCheckoutDestinations: { path: "/checkout/destination" },
    LiffCheckoutAddress: { path: "/checkout/address" },
    LiffCheckoutDelivery: { path: "/checkout/delivery" },
    LiffCheckoutPayment: { path: "/checkout/payment" },
    LiffCheckoutPaymentCreditCard: { path: "/checkout/payment/creditcard" },
    LiffPrivacyPolicy: { path: "/privacy-policy" },
    LiffTermsOfService: { path: "/terms-of-service" },
    LiffSpecificTrades: { path: "/specific-trades" },
    LiffVisitor: { path: "/visitor" },
    LiffAboutVisitorPrivileges: { path: "/visitor/privilege" },
    LiffEventReservations: { path: "/event/reservation" },


    DashboardTraffic: { path: "/dashboard/traffic-and-engagement" },
    DashboardProductAnalysis: { path: "/dashboard/product-analysis" },
    Kanban: { path: "/kanban" },
    Messages: { path: "/messages" },
    SingleMessage: { path: "/message" },
    Transactions: { path: "/transactions" },
    Tasks: { path: "/tasks" },
    Settings: { path: "/settings" },
    Calendar: { path: "/calendar" },
    Map: { path: "/map" },
    Datatables: { path: "/tables/datatables" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Pricing: { path: "/examples/pricing" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // plugins
    PluginCharts: { path: "/plugins/charts" },
    PluginCalendar: { path: "/plugins/calendar" },
    PluginDatatable: { path: "/plugins/datatable" },
    PluginMap: { path: "/plugins/map" },
    PluginDropzone: { path: "/plugins/dropzone" },
    PluginSweetAlert: { path: "/plugins/sweet-alert" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};