<?php

return [
    'LINE_MESSAGE_CHANNEL_ID' => env('LINE_MESSAGE_CHANNEL_ID'),
    'LINE_MESSAGE_CHANNEL_SECRET' => env('LINE_MESSAGE_CHANNEL_SECRET'),
    'LINE_MESSAGE_CHANNEL_TOKEN' => env('LINE_MESSAGE_CHANNEL_TOKEN'),
    'PAY_JP_API_KEY' => env('PAY_JP_API_KEY'),
];