<?php

return [
    'LINE_MESSAGE_CHANNEL_ID' => env('LINE_MESSAGE_CHANNEL_ID'),
    'LINE_MESSAGE_CHANNEL_SECRET' => env('LINE_MESSAGE_CHANNEL_SECRET'),
    'LINE_MESSAGE_CHANNEL_TOKEN' => env('LINE_MESSAGE_CHANNEL_TOKEN'),
    'MIX_LIFF_ID' => env('MIX_LIFF_ID'),
    'LIFF_CHANNEL_ID' => env('LIFF_CHANNEL_ID'),
    'MIX_PAYJP_PUBLIC_KEY' => env('MIX_PAYJP_PUBLIC_KEY'),
    'PAYJP_SECRET_KEY' => env('PAYJP_SECRET_KEY'),
    'COMMON_PASSWORD' => env('COMMON_PASSWORD'),
];