name: CI

on: 
  push:
    branches:
      - develop

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: git pull
      - run: git merge develop
      - run: npm install
      - run: npm run prod
      - run: git config --local user.email "githubaction@action.action"
      - run: git config --local user.name "githubaction"
      - run: git add .
      - run: git commit -m 'from github actions'
      - run: git push origin main
  git-push:
    needs: npm-build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main
            npm install
            npm run prod